# Run on new travis container (docker) based infrastructure
sudo: false
language: node_js
node_js:
  - "13"
  - "12"
  - "10"

install:
  - npm install -g codecov

script:
  - "npm test"
  - "npm run coverage:report"
